services:
  web:
    image: ghcr.io/i9or/basictodo:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
        restart: true
        required: true

  migrate:
    image: ghcr.io/i9or/basictodo-migrate:latest
    environment:
      - NODE_ENV=production
      - DB_PATH=/usr/db/main.sqlite
    volumes:
      - ${SERVER_DB_FOLDER}:/usr/db

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
