services:
  web:
    image: ghcr.io/i9or/basictodo:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
    command: tunnel run
