name: Lint

on:
  pull_request:
    branches: ["main"]

env:
  HUSKY: 0

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21
      - run: bun install
      - run: bun run lint
      - run: bun run type-check
