name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: pwd
      - run: ls -la
      - run: bun install
      - run: bun run coverage
